package com.br.leone.enums;

public enum TipoNotificacao {
    SOLICITACAO_ACEITA,
    SOLICITACAO_INICIADA,
    SOLICITACAO_CONCLUIDA,
    SOLICITACAO_CANCELADA,
    MENSAGEM_NOVA,
    PERFIL_PRESTADOR_APROVADO,
    CATEGORIA_SUGERIDA_APROVADA
}